"""张量级模拟内核：小 GGML 图的状态、动作、转移与固定计划回放。

这是全仓库**唯一**一份张量执行规则的实现。它原属 ``mapping/tensor_mapping/``，
按 ``mapping/ALIGNMENT_IMPLEMENTATION.md`` 迁到这里，因为窗口策略与搜索策略都要用
同一套时间和显存规则求值——规则不该隶属其中任何一个策略。

分工（见该文档 §3）：

``spec``
    不可变契约对象、输入校验与指纹。M0 不建模的东西直接拒收，不做近似。
``engine``
    状态、四个动作、固定计划回放。转移规则的唯一实现——搜索导入它，而不是自己
    再写一遍。
``layer_costs``
    把 ``modeling`` 既有的逐层成本方法（``LayerSpec.compute_seconds`` /
    ``transfer_seconds``）桥接成 ``Costs`` 的小工具。

依赖方向只有一个：``tensor_mapping → llm_infer_model``。本包**不**导入
``tensor_mapping``，也不经由它读取动作或评估策略——所以它可以在没装 ``mapping``
的条件下独立导入、加载并回放一份计划。

单位：时间一律**整数纳秒**。这与 ``modeling/llm_infer_model/`` 其余部分（浮点秒）
刻意不同；两者之间只在 ``layer_costs`` 这个边界上按
``round(seconds * 1_000_000_000)`` 转换，旧 API 的秒单位不变。
"""

from __future__ import annotations

from .engine import (
    ACTION_ADVANCE,
    ACTION_COMPUTE,
    ACTION_COPY_H2D,
    ACTION_EVICT,
    CODE_CAPACITY_EXCEEDED,
    CODE_ILLEGAL_ACTION,
    CODE_INPUT_NOT_READY,
    CODE_LIVE_VALUE_LOSS,
    CODE_RESOURCE_BUSY,
    CODE_TENSOR_IN_USE,
    REASON_ACTIONS_REMAIN_AFTER_GOAL,
    REASON_GOAL_REACHED,
    REASON_INITIAL_CAPACITY_EXCEEDED,
    REASON_UNFINISHED,
    REEVALUATION_CODES,
    STATUS_INCOMPLETE_MAPPING,
    STATUS_INFEASIBLE,
    STATUS_INVALID_MAPPING,
    STATUS_VALID,
    Action,
    EvaluationResult,
    Event,
    MappingDocument,
    MappingError,
    MappingIdentityError,
    State,
    StateSnapshot,
    WallClock,
    evaluate_mapping,
    initial_state,
    is_goal,
    legal_actions,
    load_mapping,
    transition,
    used_vram_bytes,
)
from .spec import (
    ALGORITHM_UNIFORM_COST,
    COPY_ABSENT,
    COPY_DEVICE,
    COPY_READY,
    COPY_RESERVED_COPY,
    COPY_RESERVED_OUTPUT,
    DTYPE_F32,
    LOC_DRAM,
    LOC_VRAM,
    OP_DONE,
    OP_NOT_STARTED,
    OP_RUNNING,
    ORIGIN_GGML,
    ORIGIN_SYNTHETIC,
    RESOURCE_COMPUTE,
    RESOURCE_COPY,
    ROLE_INPUT,
    ROLE_INTERMEDIATE,
    ROLE_OUTPUT,
    ROLE_WEIGHT,
    SCHEMA_VERSION,
    SEMANTIC_ADD,
    SEMANTIC_MUL_MAT,
    SEMANTIC_RELU,
    Architecture,
    ComputeCost,
    Costs,
    H2DCost,
    InitialCapacityExceeded,
    InvalidInput,
    MapperConfig,
    Mapspace,
    Operation,
    Origin,
    Scenario,
    SpecError,
    Tensor,
    Unsupported,
    Workload,
    aligned_size,
    check_initial_capacity,
    load_and_validate,
    load_workload,
    scenario_fingerprint,
    workload_fingerprint,
)

__all__ = [
    "ACTION_ADVANCE",
    "ACTION_COMPUTE",
    "ACTION_COPY_H2D",
    "ACTION_EVICT",
    "ALGORITHM_UNIFORM_COST",
    "Action",
    "Architecture",
    "CODE_CAPACITY_EXCEEDED",
    "CODE_ILLEGAL_ACTION",
    "CODE_INPUT_NOT_READY",
    "CODE_LIVE_VALUE_LOSS",
    "CODE_RESOURCE_BUSY",
    "CODE_TENSOR_IN_USE",
    "COPY_ABSENT",
    "COPY_DEVICE",
    "COPY_READY",
    "COPY_RESERVED_COPY",
    "COPY_RESERVED_OUTPUT",
    "ComputeCost",
    "Costs",
    "DTYPE_F32",
    "EvaluationResult",
    "Event",
    "H2DCost",
    "InitialCapacityExceeded",
    "InvalidInput",
    "LOC_DRAM",
    "LOC_VRAM",
    "MapperConfig",
    "MappingDocument",
    "MappingError",
    "MappingIdentityError",
    "Mapspace",
    "OP_DONE",
    "OP_NOT_STARTED",
    "OP_RUNNING",
    "ORIGIN_GGML",
    "ORIGIN_SYNTHETIC",
    "Operation",
    "Origin",
    "REASON_ACTIONS_REMAIN_AFTER_GOAL",
    "REASON_GOAL_REACHED",
    "REASON_INITIAL_CAPACITY_EXCEEDED",
    "REASON_UNFINISHED",
    "REEVALUATION_CODES",
    "RESOURCE_COMPUTE",
    "RESOURCE_COPY",
    "ROLE_INPUT",
    "ROLE_INTERMEDIATE",
    "ROLE_OUTPUT",
    "ROLE_WEIGHT",
    "SCHEMA_VERSION",
    "SEMANTIC_ADD",
    "SEMANTIC_MUL_MAT",
    "SEMANTIC_RELU",
    "STATUS_INCOMPLETE_MAPPING",
    "STATUS_INFEASIBLE",
    "STATUS_INVALID_MAPPING",
    "STATUS_VALID",
    "Scenario",
    "SpecError",
    "State",
    "StateSnapshot",
    "Tensor",
    "Unsupported",
    "WallClock",
    "Workload",
    "aligned_size",
    "check_initial_capacity",
    "evaluate_mapping",
    "initial_state",
    "is_goal",
    "legal_actions",
    "load_and_validate",
    "load_mapping",
    "load_workload",
    "scenario_fingerprint",
    "transition",
    "used_vram_bytes",
    "workload_fingerprint",
]
